name: Test de aplicacion

on: [push]

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Instalo Request
        run: |
          python -m pip install requests

      - name: Run test 1
        run: |
          cd pipeline/tests
          python test_read_html.py

      - name: Run test 2
        run: |
          cd pipeline/tests
          python test_conexion_bcra.py

      - name: Run test 2
        run: |
          cd pipeline/tests
          python test_conexion_bd.py


