name: Test de aplicacion

on: [push]

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8      

      - name: Run test
        run: |
          cd pipeline/tests
          run test_read_html.py
